version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Retrieving Redshift password..."
      - echo $REDSHIFT_PASSWORD
  build:
    commands:
      - echo "Starting the build phase..."
      - aws cloudformation deploy --template-file resdap-template.yaml --stack-name resdap-stack --parameter-overrides RedshiftMasterUsername=admin RedshiftMasterUserPassword=$REDSHIFT_PASSWORD --capabilities CAPABILITY_IAM
      - echo "CloudFormation stack deployment completed"

artifacts:
  files:
    - resdap-template.yaml
  discard-paths: yes
